name: harvest-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20
  - lz4
  - python-blosc
  - requests
  - dask=2.30.0
  - distributed=2.30.0
  - tornado=6.0.4
  - dask-kubernetes=0.11.0
  - dask-gateway=0.8.0
  - numba=0.48
  - cloudpickle=1.6
  - prefect=0.13.8
  - geopandas
  - xlrd
  - lxml
  - pika
  - fsspec
  - s3fs
  - boto3
  - fastparquet
  - cmocean
  - loguru
  - zarr
  - xarray
  - netcdf4
  - h5netcdf
  - ipython
  - progressbar2
  - pydap
  - siphon
  - pip:
      # TODO: Need to figure out pangeo-forge dependency ...
      - git+https://github.com/pangeo-forge/pangeo-forge.git@0.1.0
      - git+https://github.com/ooi-data/ooi-harvester.git@main
      - gspread==3.6