name: Test Images

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'

env:
  DOCKER_ORG: cormorack
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [harvester-worker]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          DOCKER_TAG=PR
          IMAGE_SPEC="${DOCKER_ORG}/${{ matrix.IMAGE }}:${DOCKER_TAG}"
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.IMAGE }}
          push: false
          tags: |
            ${{ env.IMAGE_SPEC }}